language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
bundler_args: --without development production --quiet
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - jdyer@spreecommerce.com
    - brian@spreecommerce.com
  irc: "irc.freenode.org#spree"
matrix:
  allow_failures:
    - rvm: 2.0.0
branches:
  only:
    - master
    - 1-0-stable
    - 1-1-stable
    - 1-2-stable
    - 1-3-stable
